#!/usr/bin/env python3
"""
Generate Hunspell spell-check files for Shavian script.

Produces dialect-specific dictionaries:
  - io.joro.shaw-spell.shavian-gb.{dic,aff}
  - io.joro.shaw-spell.shavian-us.{dic,aff}

The .aff file is a static wordlist config plus the hand-curated REP table in
src/server/hunspell-replacements.txt (letter-pair swaps for basic typo
tolerance, plus directional rewrites for always-wrong decompositions of
Shavian's compound letters).

The .dic entries are augmented with Hunspell `ph:` annotations derived
from PH_RULES below. `ph:<alternate>` on a dict entry tells Hunspell: "if
the user types <alternate>, this entry is a top-ranked suggestion". Our
MAP / PHONE experiments showed Hunspell's n-gram pass silently outranks
MAP/PHONE candidates for a 77k-entry dictionary; `ph:` is the one
mechanism that reliably bubbles the canonical form to the top.

PH_RULES are applied in priority order with a cap on total variants per
word. Rules fire until the cap is hit, then later rules are skipped for
that word. This keeps disk/memory bounded while still covering all the
high-value confusion cases.

Install to ~/Library/Spelling/ for macOS spell-checking.
"""

import json
import sys
import argparse
from pathlib import Path
from collections import defaultdict


# ---- Confusion rules ----
# Applied in priority order. Each rule has `substitutes`, a list of
# (src, dst, position) tuples — all substitutes in a rule fire as a
# single group (a rule counts as one "step" against PH_CAP). Within a
# group, each substitute is tried independently and the union is taken.
#
#   position: 'any' | 'final' | 'initial'
#   dialects: set of dialects this rule applies to.
#
# Keep this list SHORT and ordered by how much value each rule adds —
# when a word hits PH_CAP variants, later rules are skipped for it.

# --- Affix flags for Shavian noun morphology ---
#
# Hunspell affixes generate plurals + possessives on the fly from singular
# noun stems, instead of bloating the .dic with every inflected form.
# Voicing rule for the sibilant suffix: 𐑩𐑟 after sibilants, 𐑕 after voiceless
# (non-sibilant) consonants, 𐑟 elsewhere.
#
# Flag assignments (single-char, the Hunspell default):
#   P — pluralise (NN1/NP0 unless uncountable). Output is also flagged R so
#       the plural can take a trailing-apostrophe possessive (𐑛𐑪𐑜𐑟 → 𐑛𐑪𐑜𐑟').
#   S — singular possessive, apostrophe-free (𐑛𐑪𐑜 → 𐑛𐑪𐑜𐑟).
#   Q — singular possessive with apostrophe (𐑛𐑪𐑜 → 𐑛𐑪𐑜'𐑟). The "camp 2"
#       writer convention; canonical apostrophe-free is generated by S.
#   R — plural possessive, trailing apostrophe only (plural already ends in
#       a sibilant, so the possessive just adds '). Applied to NN2 stems
#       directly and to P-generated plurals via the SFX P /R chain.
#
# Voicing classes (last char of stem, Shavian script):
#   voiceless non-sibilant: 𐑐 𐑑 𐑒 𐑓 𐑔   (p t k f θ)
#   sibilant:               𐑕 𐑟 𐑖 𐑠 𐑗 𐑡  (s z ʃ ʒ tʃ dʒ)
#   else (voiced consonant or vowel) takes plain 𐑟
VOICELESS_NON_SIBILANT = '𐑐𐑑𐑒𐑓𐑔'
SIBILANT = '𐑕𐑟𐑖𐑠𐑗𐑡'
ELSE_NEGATED = VOICELESS_NON_SIBILANT + SIBILANT  # used in [^...] for the catchall

PH_CAP = 8

PH_RULES = [
    {
        'id': 'happy-tensing',
        'substitutes': [
            # Bare happy ending: 𐑣𐑨𐑐𐑦 ↔ 𐑣𐑨𐑐𐑰
            ('𐑦', '𐑰', 'final'),
            # -ier comparative: 𐑰𐑟𐑦𐑼 ↔ 𐑰𐑟𐑰𐑼
            ('𐑦𐑼', '𐑰𐑼', 'final'),
            # -iest superlative: 𐑻𐑤𐑦𐑩𐑕𐑑 ↔ 𐑻𐑤𐑰𐑩𐑕𐑑
            ('𐑦𐑩𐑕𐑑', '𐑰𐑩𐑕𐑑', 'final'),
        ],
        'dialects': {'gb', 'us'},
    },
    {
        'id': 'trap-bath',
        'substitutes': [('𐑨', '𐑭', 'any')],
        'dialects': {'gb', 'us'},
    },
    # Yod-coalescence rules: one-way only (canonical dict entry grows a
    # ph: for the non-canonical alt, but not vice versa). Readlex
    # canonicalises on the non-coalesced form with 𐑿 before /uː/
    # ("tube" = 𐑑𐑿𐑚) and on the single-letter affricates elsewhere
    # ("church" = 𐑗𐑻𐑗). A user who types the coalesced/decomposed
    # alt lands on the canonical; a correct typist doesn't see the
    # non-canonical form offered back at them.
    #
    # Direction convention: (src, dst) means "in a canonical dict entry
    # containing src, produce the ph: alt by replacing with dst" — i.e.
    # src is what the dict has, dst is what we're generating as ph:.
    {
        'id': 'chew',
        'substitutes': [('𐑑𐑿', '𐑗𐑵', 'any')],
        'dialects': {'gb', 'us'},
        'symmetric': False,
    },
    {
        'id': 'church',
        'substitutes': [('𐑗', '𐑑𐑘', 'any')],
        'dialects': {'gb', 'us'},
        'symmetric': False,
    },
    {
        'id': 'jew',
        'substitutes': [('𐑛𐑿', '𐑡𐑵', 'any')],
        'dialects': {'gb', 'us'},
        'symmetric': False,
    },
    {
        'id': 'judge',
        'substitutes': [('𐑡', '𐑛𐑘', 'any')],
        'dialects': {'gb', 'us'},
        'symmetric': False,
    },
    {
        'id': 'ian',
        'substitutes': [('𐑦𐑩', '𐑾', 'any')],
        'dialects': {'gb', 'us'},
    },
    {
        'id': 'cot-caught',
        'substitutes': [('𐑪', '𐑷', 'any')],
        'dialects': {'us'},  # merger only real in GenAm
    },
    {
        'id': 'schwa-r',
        'substitutes': [('𐑩', '𐑼', 'any')],
        'dialects': {'gb', 'us'},
    },
    # Yod-drop rules: one-way only. Symmetric expansion would insert 𐑿
    # after every 𐑑/𐑛/𐑯 and produce garbage alternates.
    # Canonical forms in readlex retain the yod (𐑿); we suggest them for
    # GenAm typists who type the dropped form.
    {
        'id': 'yod-drop-t',
        'substitutes': [('𐑑𐑿', '𐑑', 'any')],
        'dialects': {'gb', 'us'},
        'symmetric': False,
    },
    {
        'id': 'yod-drop-d',
        'substitutes': [('𐑛𐑿', '𐑛', 'any')],
        'dialects': {'gb', 'us'},
        'symmetric': False,
    },
    {
        'id': 'yod-drop-n',
        'substitutes': [('𐑯𐑿', '𐑯', 'any')],
        'dialects': {'gb', 'us'},
        'symmetric': False,
    },
]


def extract_lemma_from_key(key):
    """Extract lemma from readlex key format: {lemma}_{pos}_{shavian}"""
    parts = key.split('_')
    if len(parts) >= 1:
        return parts[0].lower()
    return None


def is_proper_noun(pos):
    """Check if POS tag indicates a proper noun."""
    if not pos:
        return False
    return pos == 'NP0' or pos.startswith('NP0+')


def should_include_word(lemma, preferred_dialect, wordnet_cache):
    """Dialect-filter a word using the WordNet comprehensive cache."""
    if not wordnet_cache or lemma.lower() not in wordnet_cache:
        return True
    entry = wordnet_cache[lemma.lower()]
    variants = entry.get('variants', {})
    target_dialect = 'US' if preferred_dialect == 'us' else 'GB'
    if target_dialect in variants:
        return True
    if not variants:
        return True
    return False


def calculate_character_frequencies(readlex_data):
    """Return a string of Shavian characters ordered by freq-weighted frequency."""
    from collections import Counter
    char_freq = Counter()
    for entries in readlex_data.values():
        for entry in entries:
            shaw = entry.get('Shaw', '')
            freq = entry.get('freq', 1)
            for char in shaw:
                if '\U00010450' <= char <= '\U0001047F':
                    char_freq[char] += freq
    return ''.join(c for c, _ in sorted(char_freq.items(), key=lambda x: x[1], reverse=True))


def _substitute(word, src, dst, position):
    """Replace all occurrences of src with dst at the given position."""
    if position == 'any':
        return word.replace(src, dst)
    if position == 'final':
        if word.endswith(src):
            return word[: -len(src)] + dst
        return word
    if position == 'initial':
        if word.startswith(src):
            return dst + word[len(src):]
        return word
    raise ValueError(f"unknown position: {position!r}")


def _apply_rule(variants, rule):
    """Apply all of a rule's substitutes to every current variant, returning
    the union. By default substitutes are symmetric (src↔dst); rules with
    `symmetric: False` only fire src→dst."""
    symmetric = rule.get('symmetric', True)
    result = set(variants)
    for v in variants:
        for src, dst, position in rule['substitutes']:
            swapped = _substitute(v, src, dst, position)
            if swapped != v:
                result.add(swapped)
            if symmetric:
                swapped = _substitute(v, dst, src, position)
                if swapped != v:
                    result.add(swapped)
    return result


def ph_variants_for_word(word, rules, cap=PH_CAP):
    """Apply rules in priority order, Cartesian product, capped at `cap`
    total variants (including the original). Rules that would push past
    the cap are skipped for this word."""
    variants = {word}
    for rule in rules:
        if len(variants) >= cap:
            break
        expanded = _apply_rule(variants, rule)
        if len(expanded) > cap:
            # Would exceed cap — skip this rule rather than truncating
            # arbitrarily, so higher-priority rules aren't half-applied.
            continue
        variants = expanded
    variants.discard(word)
    return variants


def generate_simple_wordlist(readlex_data, output_dic, output_aff,
                             dialect='gb', wordnet_cache=None):
    """Generate Hunspell .dic + .aff for one dialect."""
    dialect_name = "British (GB)" if dialect == 'gb' else "American (US)"
    print(f"Generating Hunspell spell-check files for {dialect_name}...")

    # Collect unique Shavian words, filtered by dialect + proper-noun state.
    # Per-shaw flag inputs accumulate across all senses sharing a spelling:
    #   takes_singular_poss — any NN1/NP0 sense
    #   takes_plural        — any NN1/NP0 sense
    #   takes_plural_poss   — any NN2 sense (pluralia tantum: 'alms' → 'alms')
    # Uncountability isn't gated: virtually every "uncountable" noun has a
    # kinds-of-X plural sense ("milks", "waters") or a verb form that takes
    # the same -s, so the Hunspell flat-string check would accept it anyway.
    has_proper_sense = defaultdict(bool)
    has_common_sense = defaultdict(bool)
    takes_singular_poss = defaultdict(bool)
    takes_plural = defaultdict(bool)
    takes_plural_poss = defaultdict(bool)
    namer_dot = '·'

    if dialect == 'gb':
        target_variants = {'RRP', 'GB', 'RSSB', 'TrapBath', 'RRPVar', 'RRPvar', 'SSB', 'GenAus'}
    else:
        target_variants = {'GenAm', 'RSSB', 'GenAus'}

    for key, entries in readlex_data.items():
        lemma = extract_lemma_from_key(key)
        for entry in entries:
            shaw = entry.get('Shaw', '')
            if not shaw:
                continue
            var = entry.get('var', '')
            if var and var not in target_variants:
                if lemma and wordnet_cache:
                    if not should_include_word(lemma, dialect, wordnet_cache):
                        continue
                else:
                    continue
            elif not var and lemma and wordnet_cache:
                if not should_include_word(lemma, dialect, wordnet_cache):
                    continue
            pos = entry.get('pos', '')
            if is_proper_noun(pos):
                has_proper_sense[shaw] = True
                takes_singular_poss[shaw] = True
                takes_plural[shaw] = True
            else:
                has_common_sense[shaw] = True
                # Singular common nouns (NN1) take possessive + plural.
                # Pluralia tantum (NN2) take only the trailing-' plural possessive.
                # NN0 (number-neutral) and other N* tags we leave alone for now.
                if pos == 'NN1':
                    takes_singular_poss[shaw] = True
                    takes_plural[shaw] = True
                elif pos == 'NN2':
                    takes_plural_poss[shaw] = True

    shavian_words = set()
    for shaw in set(has_proper_sense) | set(has_common_sense):
        if has_common_sense[shaw]:
            shavian_words.add(shaw)
        if has_proper_sense[shaw] and not shaw.startswith(namer_dot):
            shavian_words.add(namer_dot + shaw)

    # Propagate noun flags from the bare form to the namer-dot-prefixed
    # proper-noun form (the suffix decision still keys off the same final char).
    for shaw in list(takes_singular_poss):
        if has_proper_sense[shaw]:
            takes_singular_poss[namer_dot + shaw] = True
    for shaw in list(takes_plural):
        if has_proper_sense[shaw]:
            takes_plural[namer_dot + shaw] = True

    sorted_words = sorted(shavian_words)
    print(f"Found {len(sorted_words)} unique Shavian words for {dialect_name}")
    print(f"  with plural flag (P):           {sum(1 for w in sorted_words if takes_plural[w])}")
    print(f"  with singular-poss flag (S+Q):  {sum(1 for w in sorted_words if takes_singular_poss[w])}")
    print(f"  with plural-poss flag (R only): {sum(1 for w in sorted_words if takes_plural_poss[w] and not takes_plural[w])}")

    applicable_rules = [r for r in PH_RULES if dialect in r['dialects']]
    print(
        f"Applying {len(applicable_rules)} ph: rule(s) in priority order "
        f"(cap={PH_CAP}): {', '.join(r['id'] for r in applicable_rules)}"
    )

    print(f"Writing {output_dic}...")
    total_ph = 0
    max_ph = 0
    capped_words = 0
    with open(output_dic, 'w', encoding='utf-8') as f:
        f.write(f"{len(sorted_words)}\n")
        for word in sorted_words:
            variants = ph_variants_for_word(word, applicable_rules)
            total_ph += len(variants)
            if len(variants) + 1 >= PH_CAP:  # +1 for the original
                capped_words += 1
            if len(variants) > max_ph:
                max_ph = len(variants)

            # Affix flags. P generates the plural (which itself carries R for
            # plural-possessive); S and Q generate singular possessives.
            # NN2 stems get R directly so their bare possessive (alms') works.
            flags = ''
            if takes_plural[word]:
                flags += 'P'
            if takes_singular_poss[word]:
                flags += 'SQ'
            if takes_plural_poss[word] and 'P' not in flags:
                flags += 'R'

            stem = f'{word}/{flags}' if flags else word

            if variants:
                suffix = ' '.join(f'ph:{v}' for v in sorted(variants))
                f.write(f'{stem} {suffix}\n')
            else:
                f.write(f'{stem}\n')
    print(f"  {total_ph} ph: annotations across {len(sorted_words)} entries "
          f"(max {max_ph}/word, {capped_words} words hit cap)")

    print(f"Writing {output_aff}...")
    print("Calculating character frequencies for TRY optimization...")
    try_chars = calculate_character_frequencies(readlex_data)
    print(f"TRY string: {try_chars[:20]}... (top 20 chars)")

    replacements_file = Path(__file__).parent / 'hunspell-replacements.txt'
    replacement_rules = ""
    if replacements_file.exists():
        with open(replacements_file, 'r', encoding='utf-8') as rep_file:
            replacement_rules = rep_file.read().strip() + "\n\n"

    with open(output_aff, 'w', encoding='utf-8') as f:
        f.write("# Hunspell affix file for Shavian script\n")
        f.write(f"# Configuration for {dialect_name}\n\n")
        f.write("SET UTF-8\n")
        f.write("# TRY: characters ordered by frequency for suggestion ranking\n")
        f.write(f"TRY {try_chars}\n\n")
        f.write("# Word characters include Shavian letters, hyphen, namer dot,\n")
        f.write("# and ASCII apostrophe (for possessive-with-apostrophe forms).\n")
        f.write("WORDCHARS 𐑐𐑑𐑒𐑓𐑔𐑕𐑖𐑗𐑘𐑙𐑚𐑛𐑜𐑝𐑞𐑟𐑠𐑡𐑢𐑣𐑤𐑥𐑦𐑧𐑨𐑩𐑪𐑫𐑬𐑭𐑮𐑯𐑰𐑱𐑲𐑳𐑴𐑵𐑶𐑷𐑸𐑹𐑺𐑻𐑼𐑽𐑾𐑿-·'\n\n")
        if replacement_rules:
            f.write(replacement_rules)

        # --- Noun morphology affixes ---
        # See generate_spellcheck.py header comment for the full design;
        # voicing rule: sibilant → 𐑩𐑟, voiceless-non-sibilant → 𐑕, else → 𐑟.
        f.write("# --- Noun plural and possessive affixes ---\n")
        f.write("# Voicing-conditioned suffixes generated from singular noun stems.\n\n")

        # Plural (P). Output flagged R so the plural takes the trailing-'
        # plural-possessive suffix (𐑛𐑪𐑜𐑟 → 𐑛𐑪𐑜𐑟').
        f.write("SFX P Y 3\n")
        f.write(f"SFX P 0 𐑩𐑟/R [{SIBILANT}]\n")
        f.write(f"SFX P 0 𐑕/R   [{VOICELESS_NON_SIBILANT}]\n")
        f.write(f"SFX P 0 𐑟/R   [^{ELSE_NEGATED}]\n\n")

        # Singular possessive, apostrophe-free canonical form (S).
        f.write("SFX S Y 3\n")
        f.write(f"SFX S 0 𐑩𐑟 [{SIBILANT}]\n")
        f.write(f"SFX S 0 𐑕   [{VOICELESS_NON_SIBILANT}]\n")
        f.write(f"SFX S 0 𐑟   [^{ELSE_NEGATED}]\n\n")

        # Singular possessive with apostrophe (Q). Convention is always '𐑟,
        # not voicing-conditioned — the apostrophe acts as a grammatical
        # marker followed by canonical 𐑟, regardless of stem.
        f.write("SFX Q Y 1\n")
        f.write("SFX Q 0 '𐑟 .\n\n")

        # Plural possessive (R). Plural already ends in a sibilant; possessive
        # is just a trailing apostrophe.
        f.write("SFX R Y 1\n")
        f.write("SFX R 0 ' .\n\n")

        f.write("# Confusion-class suggestions are driven by ph: annotations on\n")
        f.write("# the .dic entries (see PH_RULES in generate_spellcheck.py).\n")

    print("Hunspell files generated successfully!")
    print(f"  - {output_dic} ({len(sorted_words)} words)")
    print(f"  - {output_aff}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate Hunspell spell-check files for Shavian script'
    )
    parser.add_argument(
        '--dialect', choices=['gb', 'us', 'both'], default='both',
        help='Which dialect(s) to generate: gb, us, or both'
    )
    args = parser.parse_args()

    script_dir = Path(__file__).parent
    project_dir = script_dir.parent.parent
    readlex_path = project_dir / 'data/readlex.json'
    wordnet_cache_path = project_dir / 'data/wordnet-comprehensive.json'
    build_dir = project_dir / 'build'

    build_dir.mkdir(exist_ok=True)

    print("Loading readlex data...")
    with open(readlex_path, 'r', encoding='utf-8') as f:
        readlex_raw = json.load(f)
    readlex_data = {}
    for key, value in readlex_raw.items():
        readlex_data[key] = [value] if isinstance(value, dict) else value
    print(f"Loaded {len(readlex_data)} readlex entries\n")

    wordnet_cache = {}
    if wordnet_cache_path.exists():
        print("Loading comprehensive WordNet cache...")
        with open(wordnet_cache_path, 'r', encoding='utf-8') as f:
            wordnet_cache = json.load(f)
        print(f"Loaded cache with {len(wordnet_cache)} lemmas\n")
    else:
        print(f"WARNING: Comprehensive cache not found at {wordnet_cache_path}")
        print("Dialect filtering will not work properly. Run 'make wordnet-cache' first.\n")

    dialects_to_generate = ['gb', 'us'] if args.dialect == 'both' else [args.dialect]

    for dialect in dialects_to_generate:
        dic_path = build_dir / f'io.joro.shaw-spell.shavian-{dialect}.dic'
        aff_path = build_dir / f'io.joro.shaw-spell.shavian-{dialect}.aff'
        generate_simple_wordlist(
            readlex_data, dic_path, aff_path, dialect,
            wordnet_cache=wordnet_cache,
        )
        print()

    print("All spell-check files ready!")
    print(f"To install GB: cp {build_dir}/io.joro.shaw-spell.shavian-gb.* ~/Library/Spelling/")
    print(f"To install US: cp {build_dir}/io.joro.shaw-spell.shavian-us.* ~/Library/Spelling/")
    print("Or run: make spellcheck install")


if __name__ == '__main__':
    main()
